#!/usr/bin/env bash
# script that displays To infinity and beyond indefinitely.

function no_ctrlc()
{
    echo "I am invincible!!!"
}


trap no_ctrlc SIGTERM

while :
do
    echo "To infinity and beyond"
    sleep 2
done
